minimumReleaseAge: 0
verifyDepsBeforeRun: false
onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - spawn-sync
allowBuilds:
  core-js: set this to true or false
  esbuild: true
  sharp: true
  spawn-sync: true
