/** Golden capsule fixtures used by the parser tests. */

// A complete, well-formed capsule (Electrical) wrapped in a stemlm fence.
export const FENCED_ELECTRICAL = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Electrical',
  'topic: Series resistor voltage',
  '@endmeta',
  '@step',
  'title: Label the circuit',
  '@formula',
  '$$V = IR$$',
  '@endformula',
  '@body',
  'We have a $12\\,\\text{V}$ source in series with $R_1$ and $R_2$.',
  '@endbody',
  '@diagram type=svg',
  '<svg viewBox="0 0 200 100"><line x1="0" y1="50" x2="200" y2="50" stroke="black"/><text x="10" y="40">12V</text></svg>',
  '@enddiagram',
  '@takeaway',
  'Series elements share the same current.',
  '@endtakeaway',
  '@quickcheck',
  'q: What is shared in a series circuit?',
  'a: The current.',
  '@endquickcheck',
  '@followup',
  'Show how this changes if R2 is doubled.',
  '@endfollowup',
  '@endstep',
  '@step',
  'title: Solve for current',
  '@body',
  'Total resistance is $R_1 + R_2 = 6\\,\\Omega$, so $I = 2\\,\\text{A}$.',
  '@endbody',
  '@endstep',
  '@solution',
  'The current is $2\\,\\text{A}$ and the drop across $R_1$ is $4\\,\\text{V}$.',
  '@diagram type=mermaid',
  'graph LR; V-->R1-->R2-->V',
  '@enddiagram',
  'Done.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

// Same content but the model dropped the closing terminators on some blocks.
export const TOLERANT_PARTIAL = [
  '@meta',
  'subject: Math',
  'topic: Derivative of x squared',
  '@endmeta',
  '@step',
  'title: Apply the power rule',
  '@body',
  'For $f(x)=x^2$, bring down the exponent.',
  '@step',
  'title: Result',
  '@body',
  '$$f\'(x) = 2x$$',
  '@end',
].join('\n');

// No capsule at all.
export const NO_CAPSULE = 'Sure! The derivative of x^2 is 2x. Let me know if you want more detail.';

// Capsule preceded by chatty preamble + trailing text (realistic chatbot output).
export const NOISY_FENCED = [
  "Here's your structured breakdown:",
  '',
  '```stemlm',
  '@meta',
  'subject: Biology',
  'topic: Mitosis phases',
  '@endmeta',
  '@step',
  'title: Prophase',
  '@body',
  'Chromosomes condense.',
  '@endstep',
  '@solution',
  'Mitosis has four main phases.',
  '@endsolution',
  '@end',
  '```',
  '',
  'Hope that helps!',
].join('\n');
