/**
 * Structural capsule fixtures for parser/render tests only.
 * These are format smoke tests — NOT pre-authored exam solutions.
 * Real answers and diagrams come from Gemini at runtime.
 */

const MINIMAL_SVG =
  '<svg viewBox="0 0 300 180"><line x1="20" y1="90" x2="280" y2="90" stroke="#333" stroke-width="2"/><text x="30" y="80" font-size="14">label</text></svg>';

const OPAMP_SVG =
  '<svg viewBox="0 0 300 180"><polygon points="120,60 200,90 120,120" fill="none" stroke="#333"/><text x="130" y="95" font-size="14">+</text></svg>';

const FEEDBACK_SVG =
  '<svg viewBox="0 0 300 180"><rect x="80" y="70" width="40" height="20" fill="none" stroke="#333"/><text x="85" y="85" font-size="13">Rf</text><rect x="160" y="70" width="40" height="20" fill="none" stroke="#333"/><text x="165" y="85" font-size="13">Rg</text></svg>';

const DIODE_SVG =
  '<svg viewBox="0 0 300 180"><polygon points="100,80 140,90 100,100" fill="none" stroke="#333"/><circle cx="150" cy="90" r="8" fill="none" stroke="#333"/><rect x="180" y="75" width="50" height="30" fill="none" stroke="#333"/></svg>';

const WAVE_SVG =
  '<svg viewBox="0 0 300 180"><path d="M 30 120 Q 90 40 150 120 T 270 120" fill="none" stroke="#333"/><text x="40" y="50" font-size="14">wave</text></svg>';

/** Minimal electrical capsule — tests parse/render pipeline shape only. */
export const FENCED_ELECTRICAL = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Electrical',
  'topic: Circuit format check',
  'question: Structural fixture — not a stored solution.',
  '@endmeta',
  '@step',
  'title: Label the circuit',
  '@formula',
  '$$V = IR$$',
  '@endformula',
  '@body',
  '$V$ is voltage in $\\text{V}$. With $I=1\\,\\text{A}$ and $R=1\\,\\Omega$: $V=IR=1\\times1=1\\,\\text{V}$.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@takeaway',
  'Format check only.',
  '@endtakeaway',
  '@endstep',
  '@step',
  'title: Second step placeholder',
  '@body',
  'Second step demonstrates @body block structure.',
  '@endbody',
  '@endstep',
  '@solution',
  'Structural fixture — Gemini produces real solutions at runtime.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

/** Minimal math capsule — tests parse/render pipeline shape only. */
export const FENCED_MATH = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Math',
  'topic: Limits format check',
  'question: Structural fixture — not a stored exam answer.',
  '@endmeta',
  '@step',
  'title: Restate the limit',
  '@formula',
  '$$\\lim_{x\\to 0} f(x)$$',
  '@endformula',
  '@body',
  '$f(x)$ is the integrand. With $x=0.1$: substitution shows format-only work.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Apply one algebraic move',
  '@body',
  'One manipulation per step for pipeline validation.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: State the result symbolically',
  '@body',
  'Final symbolic form placeholder — Gemini produces real math at runtime.',
  '@endbody',
  '@endstep',
  '@solution',
  'Structural fixture — Gemini produces real math solutions at runtime.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

/** Minimal chemistry capsule — tests parse/render pipeline shape only. */
export const FENCED_BIOLOGY = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Biology',
  'topic: Pipeline format check',
  'question: Structural fixture — not a stored exam answer.',
  '@endmeta',
  '@step',
  'title: Introduce organelles',
  '@body',
  'Organelle labels are placeholders for format validation only.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Compare cell types',
  '@formula',
  '$$r = \\frac{V_e}{V_p}$$',
  '@endformula',
  '@body',
  '$r$ is the volume size ratio. With $V_e=100\\,\\mu\\text{m}^3$ and $V_p=1\\,\\mu\\text{m}^3$: $r=V_e/V_p=100/1=100$.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Summarize significance',
  '@body',
  'Significance step for pipeline validation.',
  '@endbody',
  '@endstep',
  '@solution',
  'Structural fixture — Gemini produces real biology solutions at runtime.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

export const FENCED_CHEMISTRY = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Chemistry',
  'topic: Stoichiometry format check',
  'question: Structural fixture — not a stored exam answer.',
  '@endmeta',
  '@step',
  'title: Identify species',
  '@body',
  'Species are placeholders for format validation only.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Write balanced form',
  '@formula',
  '$$\\ce{aA + bB -> cC}$$',
  '@endformula',
  '@body',
  '$a$ is a stoichiometric coefficient. Example format: $a=1$.',
  '@endbody',
  '@diagram type=svg',
  MINIMAL_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Check units',
  '@body',
  'Units check step for pipeline validation.',
  '@endbody',
  '@endstep',
  '@solution',
  'Structural fixture — Gemini produces real chemistry solutions at runtime.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

/** Op-amp capsule shape — parser structure test, not a verified benchmark. */
export const OPAMP_NONINVERTING = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Electrical',
  'topic: Non-inverting op-amp gain',
  '@endmeta',
  '@step',
  'title: Draw the op-amp triangle symbol',
  '@body',
  'Op-amp triangle with + and − inputs.',
  '@endbody',
  '@diagram type=svg',
  OPAMP_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Label inputs',
  '@body',
  'Non-inverting input at $V_+$.',
  '@endbody',
  '@endstep',
  '@step',
  'title: Attach the feedback resistor network',
  '@body',
  'Feedback network with $R_f$ and $R_g$.',
  '@endbody',
  '@diagram type=svg',
  FEEDBACK_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Invoke the virtual short',
  '@formula',
  '$$V_+ \\approx V_-$$',
  '@endformula',
  '@body',
  'Ideal op-amp feedback forces the virtual short.',
  '@endbody',
  '@takeaway',
  'Virtual short links the inputs.',
  '@endtakeaway',
  '@endstep',
  '@step',
  'title: Write gain relation',
  '@formula',
  '$$A_v = 1 + R_f/R_g$$',
  '@endformula',
  '@body',
  'Gain formula in symbols only for format test.',
  '@endbody',
  '@endstep',
  '@step',
  'title: Substitute component values',
  '@body',
  'Substitute given resistor values in @body when solving.',
  '@endbody',
  '@endstep',
  '@solution',
  'Non-inverting gain uses $V_{\\text{out}}$ and virtual-short analysis.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

export const OPAMP_NONINVERTING_RAILS = OPAMP_NONINVERTING;

/** Diode rectifier capsule shape — parser structure test only. */
export const DIODE_HALFWAVE_RECTIFIER = [
  '```stemlm',
  '@meta',
  'version: 1',
  'subject: Electrical',
  'topic: Half-wave diode rectifier',
  '@endmeta',
  '@step',
  'title: Draw the half-wave rectifier circuit',
  '@body',
  'Source, diode, and load resistor.',
  '@endbody',
  '@diagram type=svg',
  DIODE_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Sketch the rectified output waveform',
  '@body',
  'Positive half-cycles pass; negative blocked.',
  '@endbody',
  '@diagram type=svg',
  WAVE_SVG,
  '@enddiagram',
  '@endstep',
  '@step',
  'title: Relate peak voltage to peak current',
  '@formula',
  '$$I_p = V_p / R$$',
  '@endformula',
  '@body',
  'Peak current from peak voltage and load resistance.',
  '@endbody',
  '@endstep',
  '@solution',
  'Average voltage $V_{\\text{avg}}$ follows from the waveform integral.',
  '@endsolution',
  '@end',
  '```',
].join('\n');

export const DIODE_HALFWAVE_RECTIFIER_12V = DIODE_HALFWAVE_RECTIFIER;

export const TOLERANT_PARTIAL = [
  '@meta',
  'subject: Math',
  'topic: Derivative of x squared',
  '@endmeta',
  '@step',
  'title: Apply the power rule',
  '@body',
  'For $f(x)=x^2$, bring down the exponent.',
  '@step',
  'title: Result',
  '@body',
  '$$f\'(x) = 2x$$',
  '@end',
].join('\n');

export const NO_CAPSULE = 'Here is a normal answer with no stemLM block at all.';

export const NOISY_FENCED = [
  'Sure! Here is the breakdown:',
  '',
  '```stemlm',
  '@meta',
  'subject: Biology',
  'topic: Mitosis phases',
  '@endmeta',
  '@step',
  'title: Prophase',
  '@body',
  'Chromosomes condense.',
  '@endstep',
  '@solution',
  'Mitosis has four main phases.',
  '@endsolution',
  '@end',
  '```',
  '',
  'Hope that helps!',
].join('\n');
