/**
 * Subject playbooks. The builder appends exactly ONE of these to the core
 * protocol (chosen by the classifier or the user's override). Each gives the
 * model subject-specific guidance on atomic intermediate steps and what each
 * step's diagram should depict.
 */
import type { Subject } from './types';

export const PLAYBOOKS: Record<Subject, string> = {
  Physics: `PHYSICS (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). list knowns → name unknowns → pick principle (Newton/energy/momentum/kinematics/fields) → draw state diagram for this step → write governing equation (symbols only) → substitute one group of values → isolate target → numeric result → units & magnitude check. FREE-BODY: one isolated object, only external force arrows from its center, every arrow labeled, coordinate axes separate/aligned with incline. OPTICS: draw optical axis, lens/mirror, F/2F marks, object/image arrows, parallel/focal/central rays; label do, di, f, m and real/virtual/upright/inverted. GRAPHS/FIELDS: axes with variables+units, direction arrows, direct curve/region labels. SVG labels offset from vectors/curves; no text on strokes.`,

  Chemistry: `CHEMISTRY (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). identify species/phases → balance equation → convert to moles (one species per step) → pick controlling relation (stoich/K/rate/thermo) → substitute one value → solve for next unknown → check limiting reagent & units. mhchem: $\\ce{2H2 + O2 -> 2H2O}$. @diagram type=svg REQUIRED on visual steps — never skip when the step names draw/sketch/diagram/structure/mechanism/spectrum/orbital/energy profile/phase diagram/unit cell. Step 1 for multi-part problems: overview diagram (energy levels, MO diagram, mechanism outline, or cell schematic). MO/ENERGY: energy axis upward, AO columns outside, MO column center, σ/π/σ*/π* labels, electron arrows, dashed correlations only when useful. STRUCTURES: wedge/dash, lone pairs, charges, bond angles, resonance arrows, orbital phase/nodal-plane labels. GRAPHS/SPECTRA: axes with units and key peaks/points. COMPLETENESS: every species, orbital, bond, peak, or electrode you name in @body MUST appear labeled in that step's SVG. Use viewBox="0 0 300 180", font-size 13–15, ≥5 primitives + ≥3 labels; offset labels 10px from symbols/curves — never stacked or on bonds. Minimum ≥40% of steps carry diagrams on diagram-intensive problems.`,

  Math: `MATH (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). restate goal → name the rule for THIS line (chain/product/u-sub/partials) → apply it once → simplify one expression → substitute values → verify. Never combine two algebra manipulations in one step. Show each key line with $$…$$. SVG: graph/figure/number line showing the state after this move. GRAPHS need labelled axes, origin/ticks/scale cues, intercepts/critical points/asymptotes, direct curve/region labels; GEOMETRY needs clean points/segments/arcs, dimensions offset from edges, no text on lines.`,

  Biology: `BIOLOGY (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). name structure/process → one mechanism phase at a time → inputs for this phase → outputs → regulation/significance → common misconception. SVG (or mermaid for pathways): cell/organelle/Punnett/cycle diagram for THIS phase only. Use SBGN-like rounded glyphs/compartments, left→right or top→bottom flow, pointed arrows for activation/flow, blunt T-bars for inhibition, labels inside/adjacent to structures, no crossing label lines.`,

  CS: `CS (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). restate + constraints → pick approach → trace one operation on a concrete input → show data-structure state after that op → next op → correctness argument → time/space $O(\\cdot)$. DP: show table/array cells after each fill, highlight current subproblem, candidate transitions, chosen predecessor, final recurrence and reconstruction. Mermaid for control flow; SVG for array/tree/list/table state AT THAT STEP. Code only as inline \`code\`, never a fence.`,

  Electrical: `ELECTRICAL (one move per step): @diagram type=svg is MANDATORY on nearly EVERY step — never skip. COMPLETENESS RULE: every component you name in @body for that step MUST appear labeled in that step's SVG — partial fragments are invalid. SCHEMATIC STYLE: textbook layout with input left→right, VCC/high potential top, ground/reference bottom, grid-aligned wires, horizontal short labels, junction dots for connections, no ambiguous 4-way crossings. Standard symbols: resistor zigzag/rectangle, capacitor plates, inductor loops, diode with bar/polarity, BJT B/C/E with emitter arrow, MOSFET G/D/S/channel, op-amp triangle with +/− and feedback. Step 1 = FULL original circuit OR full small-signal model. BJT COMMON-EMITTER / HYBRID-π: draw complete schematic — BJT symbol (arrow on emitter), base B, collector C, emitter E, $r_\\pi$ base-emitter, $g_m v_{be}$ controlled source (diamond) from C to E or ground, $R_E$ unbypassed to ground, $R_C$ collector load to $V_{CC}$, $v_{in}$ at base, ground; for $R_{out}$ redraw with $v_{in}=0$ and $V_{test}$ at collector. OP-AMP: triangle +/−, $R_f$/$R_g$, rails/reference, ground, all nodes wired. DC/NODAL: every R, every source, node labels, ground, bridge connections. REQUIRED @diagram on: model drawing, $R_{in}$/$R_{out}$/$A_v$ derivations, KCL/KVL, superposition, Thevenin, source killing. Each SVG: ≥8 primitives + ≥4 labels on model steps; ≥5 primitives + ≥3 labels otherwise; never text-only. ≥55% of steps must have diagrams. Highlight what changed (dashed KCL circle, orange reduced branch). Every step needs @body with symbol defs + plug-in. AC/PHASOR: impedance triangle + phasors. Keep <text> labels ≥14px off wires.`,

  Mechanical: `MECHANICAL (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). identify body + assumptions → one free-body or thermo-state diagram → write one governing equation → substitute one term → solve for one unknown → interpret (direction/factor of safety) → units check. FBD: isolate body, external forces/moments only, dimensions/supports labelled. AXIAL/STRESS: draw bar/cylinder with outward tensile arrows P, optional internal cut N=P, circular cross-section with d, area A=πd²/4, and uniform stress σ=P/A. THERMO: P–V/T–s axes with state points and process arrows. SVG: forces/moments/stress/P-V for THIS state only.`,

  Civil: `CIVIL (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). idealise structure + supports + loads → solve for one reaction → internal forces at one section → next section → one SFD/BMD segment → stress/deflection or design check → verify equilibrium. BEAMS/TRUSSES: standard pin/roller/fixed support symbols, reaction arrows, load magnitudes, spans/dimensions, member labels, section cuts. SFD/BMD: x-axis and force/moment units, load jumps, zero crossings, positive sagging convention. SVG: beam/truss with loads, then shear/moment for the section just found.`,

  Chemical: `CHEMICAL ENG (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). draw control volume + numbered streams → pick basis/assumptions → write one total or component balance → add equilibrium/transport only when needed → solve one unknown → stream table (total, component flows, compositions, units) → check conservation. SVG: PFD/control volume with labelled unit, numbered flow arrows, stream totals/compositions/units, and highlight the stream or balance used in THIS step. Equilibrium/operating plots need labelled axes and operating points.`,

  General: `GENERAL: pick the most specific subject and its conventions. Break work into atomic moves: identify givens → choose principle → one manipulation per step → numeric substitution → sanity check. Every @step needs a non-empty @body with definitions + worked numbers when a formula is used. Never lump "setup" and "solve" together. Diagram = state after THIS move only.`,
};

export function getPlaybook(subject: Subject): string {
  return PLAYBOOKS[subject] ?? PLAYBOOKS.General;
}
