/**
 * Subject playbooks. The builder appends exactly ONE of these to the core
 * protocol (chosen by the classifier or the user's override). Each gives the
 * model subject-specific guidance on atomic intermediate steps and what each
 * step's diagram should depict.
 */
import type { Subject } from './types';

export const PLAYBOOKS: Record<Subject, string> = {
  Physics: `PHYSICS (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). list knowns → name unknowns → pick principle → draw the state diagram for THIS step → write the governing equation (symbols only) → substitute one group of values → isolate target → numeric result → units & magnitude/limit check.
SUBTOPIC PRINCIPLES: mechanics → Newton's laws / kinematics / work-energy / momentum / rotational dynamics / Lagrangian; oscillations & waves → SHM, superposition, standing waves, resonance, Doppler; thermodynamics → laws, ideal gas, kinetic theory, cycles; electromagnetism → Coulomb/Gauss, fields & potential, circuits, Ampère/Faraday, Maxwell; optics → reflection/refraction, lenses/mirrors, interference/diffraction; modern/quantum → photons, de Broglie, energy levels, uncertainty; nuclear → decay, binding energy.
DIAGRAM per subtopic (SVG = state AT THIS STEP only): mechanics → free-body diagram isolating ONE body with only external forces (label each force vector, axes/angles); rotation → torque & lever arms; waves → labeled wave/PV with axes+units; E&M → field lines/vectors with direction arrows, charges, equipotentials; optics → optical axis, lens/mirror, F & 2F marks, object/image arrows, the parallel/focal/central rays drawn AFTER this surface, label do,di,f,m and real/virtual/upright/inverted; energy/thermo → labeled PV or energy-level diagram; modern → energy-level ladder with transitions. Graphs need labeled axes, units, ticks, and the curve named.`,

  Chemistry: `CHEMISTRY (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). identify species/phases → balance the equation → convert to moles (one species per step) → pick the controlling relation → substitute one value → solve the next unknown → check limiting reagent & units. mhchem: $\\ce{2H2 + O2 -> 2H2O}$.
SUBTOPIC PRINCIPLES: general/stoichiometry → mole ratios, limiting reagent, % yield; physical chemistry → thermodynamics (ΔH/ΔS/ΔG), equilibrium K, kinetics (rate laws, Arrhenius), quantum/spectra (energy levels, partition functions); organic → reaction mechanisms with curved arrows & formal charges, stereochemistry (R/S, E/Z), conformations; inorganic → periodic trends, VSEPR, MO/crystal-field; analytical → titration curves, Beer's law, spectroscopy (NMR/IR/MS/UV-Vis); electrochemistry → half-reactions, Nernst, cells.
@diagram type=svg REQUIRED on any step that draws/sketches/diagrams/names a structure/mechanism/spectrum/orbital/energy profile/phase diagram/unit cell/cell. Step 1 of multi-part problems: an overview diagram (energy levels, MO diagram, mechanism outline, or cell schematic). Each SVG = state AT THIS STEP: Lewis/line-angle structures with lone pairs & charges, VSEPR with wedge/dash, curved-arrow mechanism steps, MO energy diagram (energy axis up, AO columns outside, MO column center, σ/π/σ*/π* labels, electron arrows), reaction-coordinate profile, ICE table as labeled boxes, spectra with labeled peaks/axes, electrochemical cell with electrodes & salt bridge. COMPLETENESS: every species/bond/orbital/peak/electrode named in @body MUST appear labeled. viewBox="0 0 300 180", font-size 13–15, ≥5 primitives + ≥3 labels, offset labels 10px — never stacked or text-only. ≥40% of steps carry diagrams on diagram-intensive problems.`,

  Math: `MATH (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units where physical). restate the goal → name the rule for THIS line → apply it once → simplify ONE expression → substitute values → verify. Never combine two manipulations in one step; show each key line with $$…$$.
SUBTOPIC PRINCIPLES: algebra/precalc → factoring, identities, systems; single-variable calculus → limits (and the indeterminate form), chain/product/quotient/u-sub, FTC; multivariable → partials, gradient, multiple integrals, Jacobian, Lagrange multipliers; linear algebra → row reduction, rank/nullity, eigenvalues/eigenvectors, diagonalization; differential equations → classify (order/linearity), separable/integrating-factor/characteristic-root, series/Laplace; probability & statistics → distributions, expectation/variance, Bayes, CI/hypothesis tests; discrete → counting, recurrences, graphs, induction; complex analysis → Cauchy/residues; numerical → error bounds, iteration. Prove claims rigorously when asked (state assumptions → deduce → conclude).
DIAGRAM (SVG = state after THIS move): function graph (labeled axes/units/ticks, intercepts, asymptotes, critical points), number line, shaded region with labeled boundaries, geometry figure with labels offset from edges, vector field / phase portrait with arrowheads, contour/level curves. Omit a diagram on a purely symbolic algebra line.`,

  Biology: `BIOLOGY (one move per step): every @step needs non-empty @body (define terms, give the mechanism, compute with units when quantitative). name the structure/process → one mechanism phase at a time → inputs of this phase → outputs → regulation/significance → common misconception or quantitative check.
SUBTOPIC PRINCIPLES: cell biology → organelles, membranes, transport, cell cycle; genetics → Mendelian crosses, linkage, Hardy-Weinberg, molecular (replication/transcription/translation); physiology → homeostasis, neuro/cardio/renal/respiratory mechanisms (often quantitative); ecology → population growth, energy flow, food webs; evolution → selection, speciation, phylogenetics; microbiology → growth, metabolism, genetics; immunology → innate/adaptive responses; bioinformatics → sequence/probability reasoning.
DIAGRAM (SVG, or mermaid for linear pathways): cell/organelle/anatomy with labels adjacent to glyphs; Punnett square or pedigree; cycle (cell cycle/Krebs/Calvin) with stages; pathway flow consistent left→right or top→bottom — POINTED arrow = activation/flow, BLUNT bar (⊣) = inhibition; gel/phylogeny with labeled lanes/taxa. Avoid crossing edges and label overlap; show only THIS phase's state.`,

  CS: `CS (one move per step): every @step needs non-empty @body (define state, trace one operation, give complexity). restate + constraints → pick the approach → trace ONE operation on a concrete input → show the data-structure state after that op → next op → correctness argument → time/space $O(\\cdot)$.
SUBTOPIC PRINCIPLES: algorithms → divide-and-conquer, greedy, DP, graph traversal (BFS/DFS/Dijkstra); data structures → array/list/stack/queue/heap/tree/hash/graph invariants; DP → define the subproblem & recurrence, fill the table, reconstruct; databases → relational algebra/SQL, normalization, indexing; operating systems → scheduling, concurrency (mutex/semaphore), deadlock, memory; networking → layered model, protocols; theory → automata/grammars, decidability, NP-completeness reductions; software engineering → design, testing, complexity. Code only as inline \`code\`, never a fence.
DIAGRAM: Mermaid for control flow / sequence / state machines (quote every node label A["v = u+at"], no ( ) { } \` in labels). SVG for the array/tree/list/table/graph state AT THAT STEP — DP problems show the table cells after each fill, highlight the current subproblem, candidate transitions, and chosen predecessor.`,

  Electrical: `ELECTRICAL (one move per step): @diagram type=svg is MANDATORY on nearly EVERY step — never skip. COMPLETENESS RULE: every component named in @body for that step MUST appear labeled in that step's SVG — partial fragments are invalid. Step 1 = FULL original circuit OR full small-signal model.
SUBTOPIC PRINCIPLES: DC/AC circuits → Ohm/KVL/KCL, series-parallel reduction, nodal/mesh, Thévenin/Norton, superposition, source transformation; phasors/AC → impedance, resonance, power factor; analog → diode/BJT/MOSFET/op-amp small-signal; signals/systems → transfer functions, Laplace/Fourier, Bode; digital → logic gates, truth tables, flip-flops; power → per-unit, Ybus, power flow; control → PID, stability.
STANDARD SYMBOLS & LAYOUT: signal flow left→right, high potential/VCC at top, ground at bottom; resistor (zigzag/box), capacitor (parallel plates), inductor (coils), diode (triangle+bar), BJT (circle+arrow on emitter), MOSFET, op-amp (triangle, + and −), dependent source (diamond), independent source (circle), ground symbol; junction dots at real connections, no ambiguous 4-way crossings. BJT HYBRID-π: base B, collector C, emitter E, $r_\\pi$, $g_m v_{be}$ source (diamond) C→E, $R_E$ to ground, $R_C$ to $V_{CC}$, $v_{in}$ at base; for $R_{out}$ set $v_{in}=0$, apply $V_{test}$ at collector. OP-AMP: triangle +/−, $R_f$/$R_g$ feedback, rails, ground, all nodes wired. PHASOR: Re/Im axes with arrowheads, label values at the projection foot, currents beside the arrowhead — never on the stroke.
REQUIRED @diagram on: model drawing, $R_{in}$/$R_{out}$/$A_v$ derivations, KCL/KVL, superposition, Thévenin, source killing. Each SVG: ≥8 primitives + ≥4 labels on model steps; ≥5 primitives + ≥3 labels otherwise; never text-only. ≥55% of steps have diagrams. Highlight what changed (dashed KCL loop, recolored reduced branch). Keep <text> labels ≥10px off wires; name components (R1,L1,Vs,Id).`,

  Mechanical: `MECHANICAL (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). identify the body + assumptions → draw ONE free-body or thermo-state diagram → write one governing equation → substitute one term → solve one unknown → interpret (direction / factor of safety) → units check.
SUBTOPIC PRINCIPLES: statics/dynamics → equilibrium, FBDs, kinematics/kinetics; mechanics of materials → axial/shear/bending/torsion stress, strain, Young's modulus, factor of safety; machine elements → shafts, gears, cams, linkages, bearings; thermodynamics → cycles (Carnot/Otto/Rankine), heat engines, refrigeration; fluid mechanics → Bernoulli, continuity, Reynolds, viscosity; vibrations → natural frequency, damping.
DIAGRAM (SVG = THIS state only): FBD isolating one body with labeled external forces/moments & axes; stress element or cross-section (e.g. bar with tensile arrows P, internal cut N=P, circular section with d, area A=πd²/4, uniform σ=P/A); shaft/gear schematic; labeled P-V or T-S plot with axes & units; flow control volume with streamlines.`,

  Civil: `CIVIL (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). idealise the structure + supports + loads → solve ONE reaction → internal forces at ONE section → next section → one SFD/BMD segment → stress/deflection or design check → verify equilibrium.
SUBTOPIC PRINCIPLES: statics of structures → reactions, method of joints/sections for trusses; beams → shear & bending-moment diagrams, sagging/hogging, deflection; structural design → reinforced concrete / steel checks, buckling; geotechnical → soil stress, bearing capacity, retaining walls; transportation/hydraulics as applicable.
DIAGRAM (SVG = THIS state only): structure with pin (triangle) / roller (circle) supports, reaction arrows, dimensions, and applied loads (point/distributed) drawn to scale; then the SFD with load-jump steps and the area-under-shear link to the BMD; positive sagging moment plotted with a labeled x-axis and units. Show the section just solved.`,

  Chemical: `CHEMICAL ENG (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). draw the control volume + numbered streams → pick basis/assumptions → write ONE total or component balance → add equilibrium/transport relations only when needed → solve one unknown → build the stream table (total flow, component flows, compositions, units) → check conservation.
SUBTOPIC PRINCIPLES: material & energy balances → steady/unsteady, recycle/purge/bypass; thermodynamics → VLE, Raoult/fugacity, energy balances; transport → heat/mass transfer coefficients; reaction engineering → CSTR/PFR design, conversion, residence time; separations → distillation (reflux, McCabe-Thiele), absorption.
DIAGRAM (SVG = THIS step only): PFD / control-volume box with numbered inlet & outlet stream arrows, the unit (mixer/reactor/separator/exchanger) labeled, and the stream(s) or balance used in this step highlighted; equilibrium plots (x-y, T-x-y) with labeled axes when relevant.`,

  General: `GENERAL: pick the most specific subject and adopt its conventions. Break work into atomic moves: identify givens (with units) → choose the governing principle and say why it applies → one manipulation per step → numeric substitution with units → final sanity/limit check. Every @step needs a non-empty @body with symbol definitions + worked numbers when a formula is used. Never lump "setup" and "solve" together. Add a @diagram (SVG, or mermaid for flows) whenever the problem is spatial/visual — show only the state after THIS move, with labeled axes/components and labels offset from lines.`,
};

export function getPlaybook(subject: Subject): string {
  return PLAYBOOKS[subject] ?? PLAYBOOKS.General;
}
