/**
 * Subject playbooks. The builder appends exactly ONE of these to the core
 * protocol (chosen by the classifier or the user's override). Each gives the
 * model subject-specific guidance on atomic intermediate steps and what each
 * step's diagram should depict.
 */
import type { Subject } from './types';

export const PLAYBOOKS: Record<Subject, string> = {
  Physics: `PHYSICS (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). list knowns → name unknowns → pick principle (Newton/energy/momentum/kinematics/fields) → draw state diagram for this step → write governing equation (symbols only) → substitute one group of values → isolate target → numeric result → units & magnitude check. OPTICS: draw optical axis, lens/mirror, F/2F marks, object/image arrows, parallel/focal/central rays; label do, di, f, m and real/virtual/upright/inverted. SVG: force arrows, rays after THIS surface, field vectors — labelled for the current state only.`,

  Chemistry: `CHEMISTRY (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). identify species/phases → balance equation → convert to moles (one species per step) → pick controlling relation (stoich/K/rate/thermo) → substitute one value → solve for next unknown → check limiting reagent & units. mhchem: $\\ce{2H2 + O2 -> 2H2O}$. SVG: structures/energy profile/ICE table for THIS stage only.`,

  Math: `MATH (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). restate goal → name the rule for THIS line (chain/product/u-sub/partials) → apply it once → simplify one expression → substitute values → verify. Never combine two algebra manipulations in one step. Show each key line with $$…$$. SVG: graph/figure/number line showing the state after this move.`,

  Biology: `BIOLOGY (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). name structure/process → one mechanism phase at a time → inputs for this phase → outputs → regulation/significance → common misconception. SVG (or mermaid for pathways): cell/organelle/Punnett/cycle diagram for THIS phase only.`,

  CS: `CS (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). restate + constraints → pick approach → trace one operation on a concrete input → show data-structure state after that op → next op → correctness argument → time/space $O(\\cdot)$. DP: show table/array cells after each fill, highlight current subproblem, candidate transitions, chosen predecessor, final recurrence and reconstruction. Mermaid for control flow; SVG for array/tree/list/table state AT THAT STEP. Code only as inline \`code\`, never a fence.`,

  Electrical: `ELECTRICAL (one move per step): @diagram type=svg is MANDATORY — never skip on circuit problems. Step 1 MUST show the FULL original circuit: every resistor (zigzag), every source (circle V or arrowed I), all node labels (A,B,C,D…), ground (3-bar symbol), dependent sources, and bridge/midpoint connections. REQUIRED @diagram on: node labeling, ground selection, KCL/KCL setup, branch reduction, superposition (each killed source), Thevenin/Norton (R removed, test source), source killing — any topology change. Each SVG must use line/path/polyline/rect/circle — never text-only placeholders. Minimum: ≥1 diagram per 2–3 steps; never <3 diagrams on multi-node circuits. Redraw circuit state AT THIS STEP; highlight what changed (dashed circle at KCL node, orange box on reduced branch). parallel RLC — compute branch admittances $Y_R=1/R$, $Y_L=1/(jX_L)$, $Y_C=j\omega C$, sum for $Y_\text{eq}$, then branch currents; every step still needs @body with symbol defs + plug-in (never formula-only). @quickcheck must test the step you just did — never generic trivia with a one-word answer. label nodes & reference directions → pick method (series-parallel/KVL/KCL/node/mesh/Thevenin/Norton) → write one equation or one reduction → simplify one branch at a time → back-substitute one unknown → check power balance. EVERY @step with @formula: @body must define symbols and show numeric substitution with units. NODE-VOLTAGE/MESH: mark reference ground; label each node; show node-voltage variables below each node; arrowheads on branch-current lines; dashed stroke-dasharray circle at KCL cut-set; current-source = circle + internal arrowed line. AC/PHASOR: separate steps for $\\omega$, $X_L$, $X_C$ → draw impedance triangle and phasors. OP-AMP/DIODE: draw circuit symbol each time topology matters. Keep <text> labels ≥14px off conductor lines.`,

  Mechanical: `MECHANICAL (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). identify body + assumptions → one free-body or thermo-state diagram → write one governing equation → substitute one term → solve for one unknown → interpret (direction/factor of safety) → units check. AXIAL/STRESS: draw bar/cylinder with outward tensile arrows P, optional internal cut N=P, circular cross-section with d, area A=πd²/4, and uniform stress σ=P/A. SVG: forces/moments/stress/P-V for THIS state only.`,

  Civil: `CIVIL (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). idealise structure + supports + loads → solve for one reaction → internal forces at one section → next section → one SFD/BMD segment → stress/deflection or design check → verify equilibrium. BEAMS: show pin/roller supports, reaction arrows, dimensions, load jumps in SFD, area-under-shear link, positive sagging BMD, x-axis and units. SVG: beam/truss with loads, then shear/moment for the section just found.`,

  Chemical: `CHEMICAL ENG (one move per step): every @step needs non-empty @body (define symbols, substitute givens, compute with units). draw control volume + numbered streams → pick basis/assumptions → write one total or component balance → add equilibrium/transport only when needed → solve one unknown → stream table (total, component flows, compositions, units) → check conservation. SVG: PFD/control volume with the stream or balance used in THIS step.`,

  General: `GENERAL: pick the most specific subject and its conventions. Break work into atomic moves: identify givens → choose principle → one manipulation per step → numeric substitution → sanity check. Every @step needs a non-empty @body with definitions + worked numbers when a formula is used. Never lump "setup" and "solve" together. Diagram = state after THIS move only.`,
};

export function getPlaybook(subject: Subject): string {
  return PLAYBOOKS[subject] ?? PLAYBOOKS.General;
}
