import type { Session, Diagram } from '@/src/protocol/types';
import { MathMarkdown } from './MathMarkdown';
import { solutionDiagramRegexGlobal } from '@/src/protocol/parser';

export function diagramKey(scope: string, i: number): string {
  return `${scope}-${i}`;
}

function ResolvedDiagram({ svg }: { svg?: string }) {
  if (!svg) return null;
  return <div className="slm-report-diagram" dangerouslySetInnerHTML={{ __html: svg }} />;
}

export function Report({
  session,
  diagramSvg,
}: {
  session: Session;
  diagramSvg: Record<string, string>;
}) {
  const { meta, steps, solution } = session.capsule;
  const date = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const solutionParts = solution.split(solutionDiagramRegexGlobal());
  const question = (session.question || meta.topic || '').trim();

  return (
    <div className="slm-report">
      <header className="slm-report-cover">
        <div className="slm-report-brand">
          <span className="slm-report-brand-stem">stem</span>
          <span className="slm-report-brand-lm">LM</span>
        </div>
        {meta.topic && <h1 className="slm-report-topic">{meta.topic}</h1>}
        <div className="slm-report-meta">
          <span className="slm-report-chip">{meta.subject}</span>
          <span className="slm-report-date">{date}</span>
        </div>
      </header>

      {question && (
        <section className="slm-report-q">
          <div className="slm-report-q-label">Question</div>
          <div className="slm-report-q-text">{question}</div>
        </section>
      )}

      <section className="slm-report-a">
        <div className="slm-report-a-label">Answer</div>
        <div className="slm-report-a-body">
          {steps.map((step) => (
            <div key={step.id} className="slm-report-step">
              <div className="slm-report-step-head">
                <span className="slm-report-step-no">
                  {String(step.index).padStart(2, '0')}
                </span>
                <h3 className="slm-report-step-title">{step.title}</h3>
              </div>
              {step.formula && (
                <div className="slm-report-formula">
                  <div className="slm-report-formula-label">Key formula</div>
                  <MathMarkdown content={step.formula} />
                </div>
              )}
              <div className="slm-report-body slm-prose">
                <MathMarkdown content={step.body} />
              </div>
              {step.diagram && (
                <ResolvedDiagram svg={diagramSvg[diagramKey('step', step.index)]} />
              )}
              {step.takeaway && (
                <div className="slm-report-takeaway">
                  <span className="slm-report-takeaway-label">Takeaway</span>
                  <MathMarkdown content={step.takeaway} />
                </div>
              )}
            </div>
          ))}

          {solution.trim() && (
            <div className="slm-report-solution">
              <h3 className="slm-report-solution-title">Solution</h3>
              <div className="slm-prose">
                {solutionParts.map((part, i) => {
                  if (i % 2 === 1) {
                    const idx = Number(part);
                    return (
                      <ResolvedDiagram key={`d-${i}`} svg={diagramSvg[diagramKey('sol', idx)]} />
                    );
                  }
                  return part.trim() ? <MathMarkdown key={`t-${i}`} content={part} /> : null;
                })}
              </div>
            </div>
          )}
        </div>
      </section>

      <footer className="slm-report-foot">
        Generated by <a href="https://stemlm.app">stemLM</a> · stemlm.app
      </footer>
    </div>
  );
}

export function collectDiagrams(session: Session): { key: string; diagram: Diagram }[] {
  const out: { key: string; diagram: Diagram }[] = [];
  for (const step of session.capsule.steps) {
    if (step.diagram) out.push({ key: diagramKey('step', step.index), diagram: step.diagram });
  }
  session.capsule.solutionDiagrams.forEach((d, i) => {
    out.push({ key: diagramKey('sol', i), diagram: d });
  });
  return out;
}
