import type { Session, Diagram } from '@/src/protocol/types';
import { MathMarkdown } from './MathMarkdown';
import { solutionDiagramRegexGlobal } from '@/src/protocol/parser';

/**
 * Static, print-styled report for PDF export. All diagrams are pre-resolved to
 * SVG strings (passed in `diagramSvg`, keyed by a stable id) so this renders
 * synchronously via renderToStaticMarkup.
 */
export function diagramKey(scope: string, i: number): string {
  return `${scope}-${i}`;
}

function ResolvedDiagram({ svg }: { svg?: string }) {
  if (!svg) return null;
  return <div className="slm-report-diagram" dangerouslySetInnerHTML={{ __html: svg }} />;
}

export function Report({
  session,
  diagramSvg,
}: {
  session: Session;
  diagramSvg: Record<string, string>;
}) {
  const { meta, steps, solution, solutionDiagrams } = session.capsule;
  const date = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  const solutionParts = solution.split(solutionDiagramRegexGlobal());
  const question = (session.question || meta.topic || '').trim();

  return (
    <article className="slm-report">
      <header className="slm-report-head">
        <div className="slm-report-brand-lockup">
          <span className="slm-report-logo-mark" aria-hidden="true" />
          <span className="slm-report-brand">stemLM</span>
        </div>
        <div className="slm-report-meta">
          <span className="slm-report-subject">{meta.subject}</span>
          <span className="slm-report-meta-sep" aria-hidden="true">
            ·
          </span>
          <time className="slm-report-date">{date}</time>
        </div>
      </header>

      <section className="slm-report-question" aria-label="Question">
        <h2 className="slm-report-section-label slm-report-label">Q.</h2>
        <div className="slm-report-q-text">{question}</div>
      </section>

      <section className="slm-report-answer" aria-label="Answer">
        <h2 className="slm-report-section-label slm-report-label">Ans.</h2>
        <div className="slm-report-a-body">
          {steps.map((step) => (
            <article key={step.id} className="slm-report-step">
              <header className="slm-report-step-head">
                <h3 className="slm-report-step-title">
                  <span className="slm-report-step-no">{step.index}.</span> {step.title}
                </h3>
              </header>
              {step.formula && (
                <div className="slm-report-formula">
                  <MathMarkdown content={step.formula} />
                </div>
              )}
              <div className="slm-report-body">
                <MathMarkdown content={step.body} />
              </div>
              {step.diagram && (
                <ResolvedDiagram svg={diagramSvg[diagramKey('step', step.index)]} />
              )}
              {step.takeaway && (
                <aside className="slm-report-takeaway">
                  <strong className="slm-report-takeaway-label">Takeaway:</strong>{' '}
                  <MathMarkdown content={step.takeaway} />
                </aside>
              )}
            </article>
          ))}

          {solution.trim() && (
            <section className="slm-report-solution">
              <header className="slm-report-solution-head">
                <h3 className="slm-report-step-title slm-report-solution-title">Solution</h3>
              </header>
              <div className="slm-report-solution-body">
                {solutionParts.map((part, i) => {
                  if (i % 2 === 1) {
                    const idx = Number(part);
                    return (
                      <ResolvedDiagram key={`d-${i}`} svg={diagramSvg[diagramKey('sol', idx)]} />
                    );
                  }
                  return part.trim() ? <MathMarkdown key={`t-${i}`} content={part} /> : null;
                })}
              </div>
            </section>
          )}
        </div>
      </section>

      <footer className="slm-report-foot">Generated by stemLM</footer>
    </article>
  );
}

/** Collect every diagram in a session, keyed for pre-rendering. */
export function collectDiagrams(session: Session): { key: string; diagram: Diagram }[] {
  const out: { key: string; diagram: Diagram }[] = [];
  for (const step of session.capsule.steps) {
    if (step.diagram) out.push({ key: diagramKey('step', step.index), diagram: step.diagram });
  }
  session.capsule.solutionDiagrams.forEach((d, i) => {
    out.push({ key: diagramKey('sol', i), diagram: d });
  });
  return out;
}
