import type { Session, Diagram } from '@/src/protocol/types';
import { MathMarkdown } from './MathMarkdown';
import { solutionDiagramRegexGlobal } from '@/src/protocol/parser';

/**
 * Static, print-styled report for PDF export. All diagrams are pre-resolved to
 * SVG strings (passed in `diagramSvg`, keyed by a stable id) so this renders
 * synchronously via renderToStaticMarkup.
 */
export function diagramKey(scope: string, i: number): string {
  return `${scope}-${i}`;
}

function ResolvedDiagram({ svg }: { svg?: string }) {
  if (!svg) return null;
  return <div className="slm-report-diagram" dangerouslySetInnerHTML={{ __html: svg }} />;
}

export function Report({
  session,
  diagramSvg,
}: {
  session: Session;
  diagramSvg: Record<string, string>;
}) {
  const { meta, steps, solution, solutionDiagrams } = session.capsule;
  const date = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
  const solutionParts = solution.split(solutionDiagramRegexGlobal());
  const question = (session.question || meta.topic || '').trim();

  return (
    <div className="slm-report">
      {/* Minimal masthead: just "stemLM" + subject/date. */}
      <header className="slm-report-head">
        <span className="slm-report-brand">stemLM</span>
        <span className="slm-report-meta">
          {meta.subject} · {date}
        </span>
      </header>

      {/* Q. — the full question. */}
      <section className="slm-report-q">
        <span className="slm-report-label">Q.</span>
        <div className="slm-report-q-text">{question}</div>
      </section>

      {/* Ans. — full step-by-step working with step diagrams (vector SVG). */}
      <section className="slm-report-a">
        <span className="slm-report-label">Ans.</span>
        <div className="slm-report-a-body">
          {steps.map((step) => (
            <div key={step.id} className="slm-report-step">
              <h3 className="slm-report-step-title">
                <span className="slm-report-step-no">{step.index}.</span> {step.title}
              </h3>
              {step.formula && (
                <div className="slm-report-formula">
                  <MathMarkdown content={step.formula} />
                </div>
              )}
              <div className="slm-report-body">
                <MathMarkdown content={step.body} />
              </div>
              {step.diagram && (
                <ResolvedDiagram svg={diagramSvg[diagramKey('step', step.index)]} />
              )}
              {step.takeaway && (
                <div className="slm-report-takeaway">
                  <strong>Takeaway:</strong> <MathMarkdown content={step.takeaway} />
                </div>
              )}
            </div>
          ))}

          {solution.trim() && (
            <div className="slm-report-solution">
              <h3 className="slm-report-step-title">Solution</h3>
              {solutionParts.map((part, i) => {
                if (i % 2 === 1) {
                  const idx = Number(part);
                  return (
                    <ResolvedDiagram key={`d-${i}`} svg={diagramSvg[diagramKey('sol', idx)]} />
                  );
                }
                return part.trim() ? <MathMarkdown key={`t-${i}`} content={part} /> : null;
              })}
            </div>
          )}
        </div>
      </section>

      <footer className="slm-report-foot">Generated by stemLM</footer>
    </div>
  );
}

/** Collect every diagram in a session, keyed for pre-rendering. */
export function collectDiagrams(session: Session): { key: string; diagram: Diagram }[] {
  const out: { key: string; diagram: Diagram }[] = [];
  for (const step of session.capsule.steps) {
    if (step.diagram) out.push({ key: diagramKey('step', step.index), diagram: step.diagram });
  }
  session.capsule.solutionDiagrams.forEach((d, i) => {
    out.push({ key: diagramKey('sol', i), diagram: d });
  });
  return out;
}
